language: node_js
node_js:
  - 14
before_install:
  - npm i -g npm@6.14.11

after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha **/**test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
