language: node_js
node_js:
  - "node"
  - "14"
env:
  global:
    - NODE_ENV=development
before_install:
  - export TZ=Europe/Helsinki
install:
  - npm install
script:
  - npm test
after_success: npm run coverage
